- hosts: localhost
  connection: local  
  tasks:
    - name: Check if Java is installed
      command: java -version
      ignore_errors: true
      register: java_check

    - name: Install Java if not already installed
      package:
        name: openjdk-17-jdk
        state: present
      when: java_check.rc != 0

    - name: Check if Jenkins is installed
      command: brew list jenkins
      register: jenkins_installed
      failed_when: false

    - name: Installing Jenkins   
      homebrew: 
        name: jenkins
        state: present
      when: jenkins_installed.rc != 0

    - name: Starting Jenkins 
      shell: 
        brew services start jenkins

    - name: Create Jenkins home directory
      file:
        path: ./jenkins
        state: directory
        owner: root
        group: owner
        mode: 0755
      become: true